name: Sync main to gh-pages

on:
  push:
    branches: [ main ]

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Git config
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
    - name: Sync main to gh-pages
      run: |
        git fetch origin gh-pages:gh-pages
        git checkout gh-pages
        git merge --ff-only origin/main
        git push origin gh-pages
